const { ClassList, Gender, Group, Month, PrismaClient } = require('@prisma/client');


const prisma = new PrismaClient();
const run = async () => {
  await prisma.admin.create({
    data: {
      username:"mohit"
    }
  })
  await prisma.class.createMany({
    data: [
      {
        id: ClassList.class_12,
        group: Group.Sunflower,
      },
      {
        id: ClassList.class_11,
        group: Group.Sunflower,
      },
      {
        id: ClassList.class_10,
        group: Group.Sunflower,
      },
      {
        id: ClassList.class_9,
        group: Group.Sunflower,
      },
      {
        id: ClassList.class_8,
        group: Group.Sunflower,
      },
      {
        id: ClassList.class_7,
        group: Group.Sunflower,
      },

      {
        id: ClassList.class_6,
        group: Group.Sunflower,
      },
      {
        id: ClassList.class_5,
        group: Group.Sunflower,
      },
      {
        id: ClassList.class_4,
        group: Group.Sunflower,
      },
    ],
  });
  await prisma.fee.createMany({
    data: [
      {
        amount: 500,
        classId: ClassList.class_4,
      },
      {
        amount: 600,
        classId: ClassList.class_5,
      },
      {
        amount: 700,
        classId: ClassList.class_6,
      },
      {
        amount: 800,
        classId: ClassList.class_7,
      },
      {
        amount: 900,
        classId: ClassList.class_8,
      },
      {
        amount: 1000,
        classId: ClassList.class_9,
      },
      {
        amount: 1100,
        classId: ClassList.class_10,
      },
      {
        amount: 1200,
        classId: ClassList.class_11,
      },
      {
        amount: 1200,
        classId: ClassList.class_12,
      },
    ],
  });
   await prisma.subject.createMany({
      data: [

         // Subjects for Class 4
         {
            subjectName: "Maths",
            classname: ClassList.class_4,
         },
         {
            subjectName: "English",
            classname: ClassList.class_4,
         },
         {
            subjectName: "Science",
            classname: ClassList.class_4,
         },
         {
            subjectName: "Social Studies",
            classname: ClassList.class_4,
         },
         {
            subjectName: "Art & Craft",
            classname: ClassList.class_4,
         },
         // Subjects for Class 5
         {
            subjectName: "Maths",
            classname: ClassList.class_5,
         },
         {
            subjectName: "English",
            classname: ClassList.class_5,
         },
         {
            subjectName: "Science",
            classname: ClassList.class_5,
         },
         {
            subjectName: "Social Studies",
            classname: ClassList.class_5,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_5,
         },
         // Subjects for Class 6
         {
            subjectName: "Maths",
            classname: ClassList.class_6,
         },
         {
            subjectName: "English",
            classname: ClassList.class_6,
         },
         {
            subjectName: "Science",
            classname: ClassList.class_6,
         },
         {
            subjectName: "Social Studies",
            classname: ClassList.class_6,
         },
         {
            subjectName: "Hindi",
            classname: ClassList.class_6,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_6,
         },
         // Subjects for Class 7
         {
            subjectName: "Maths",
            classname: ClassList.class_7,
         },
         {
            subjectName: "English",
            classname: ClassList.class_7,
         },
         {
            subjectName: "Science",
            classname: ClassList.class_7,
         },
         {
            subjectName: "Social Studies",
            classname: ClassList.class_7,
         },
         {
            subjectName: "Hindi",
            classname: ClassList.class_7,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_7,
         },
         // Subjects for Class 8
         {
            subjectName: "Maths",
            classname: ClassList.class_8,
         },
         {
            subjectName: "English",
            classname: ClassList.class_8,
         },
         {
            subjectName: "Science",
            classname: ClassList.class_8,
         },
         {
            subjectName: "Social Studies",
            classname: ClassList.class_8,
         },
         {
            subjectName: "Hindi",
            classname: ClassList.class_8,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_8,
         },
         // Subjects for Class 9
         {
            subjectName: "Maths",
            classname: ClassList.class_9,
         },
         {
            subjectName: "English",
            classname: ClassList.class_9,
         },
         {
            subjectName: "Science",
            classname: ClassList.class_9,
         },
         {
            subjectName: "Social Studies",
            classname: ClassList.class_9,
         },
         {
            subjectName: "Hindi",
            classname: ClassList.class_9,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_9,
         },
         // Subjects for Class 10
         {
            subjectName: "Maths",
            classname: ClassList.class_10,
         },
         {
            subjectName: "English",
            classname: ClassList.class_10,
         },
         {
            subjectName: "Science",
            classname: ClassList.class_10,
         },
         {
            subjectName: "Social Studies",
            classname: ClassList.class_10,
         },
         {
            subjectName: "Hindi",
            classname: ClassList.class_10,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_10,
         },
         // Subjects for Class 11
         {
            subjectName: "Maths",
            classname: ClassList.class_11,
         },
         {
            subjectName: "English",
            classname: ClassList.class_11,
         },
         {
            subjectName: "Physics",
            classname: ClassList.class_11,
         },
         {
            subjectName: "Chemistry",
            classname: ClassList.class_11,
         },
         {
            subjectName: "Biology",
            classname: ClassList.class_11,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_11,
         },
         {
            subjectName: "Economics",
            classname: ClassList.class_11,
         },
         {
            subjectName: "History",
            classname: ClassList.class_11,
         },
         // Subjects for Class 12
         {
            subjectName: "Maths",
            classname: ClassList.class_12,
         },
         {
            subjectName: "English",
            classname: ClassList.class_12,
         },
         {
            subjectName: "Physics",
            classname: ClassList.class_12,
         },
         {
            subjectName: "Chemistry",
            classname: ClassList.class_12,
         },
         {
            subjectName: "Biology",
            classname: ClassList.class_12,
         },
         {
            subjectName: "Computer Science",
            classname: ClassList.class_12,
         },
         {
            subjectName: "Economics",
            classname: ClassList.class_12,
         },
         {
            subjectName: "History",
            classname: ClassList.class_12,
         },
      ],
   });

   await prisma.student.createMany({
      data: [
         // Class 4 Students
         {
            username: "student1-class4",
            firstname: "Aarav",
            lastname: "Gupta",
            motherName: "Neelam",
            fatherName: "Vijay",
            gender: Gender.Male,
            contactNo: "1234567001",
            address: "Green Park",
            feesPaidUpto: Month.March,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "15/04/2013",
         },
         {
            username: "student2-class4",
            firstname: "Mahi",
            lastname: "Kaur",
            motherName: "Simran",
            fatherName: "Karan",
            gender: Gender.Female,
            contactNo: "1234567002",
            address: "Blue Ridge",
            feesPaidUpto: Month.April,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "21/06/2013",
         },
         {
            username: "student3-class4",
            firstname: "Raghav",
            lastname: "Sharma",
            motherName: "Priya",
            fatherName: "Rajesh",
            gender: Gender.Male,
            contactNo: "1234567003",
            address: "Oakwood Heights",
            feesPaidUpto: Month.May,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "30/08/2013",
         },
         {
            username: "student4-class4",
            firstname: "Anaya",
            lastname: "Yadav",
            motherName: "Komal",
            fatherName: "Amit",
            gender: Gender.Female,
            contactNo: "1234567004",
            address: "Palm Grove",
            feesPaidUpto: Month.June,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "10/10/2013",
         },
         {
            username: "student5-class4",
            firstname: "Vihan",
            lastname: "Mehta",
            motherName: "Rina",
            fatherName: "Ravi",
            gender: Gender.Male,
            contactNo: "1234567005",
            address: "Sunset Boulevard",
            feesPaidUpto: Month.May,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "25/12/2013",
         },
         {
            username: "student6-class4",
            firstname: "Ishika",
            lastname: "Nair",
            motherName: "Sonia",
            fatherName: "Kumar",
            gender: Gender.Female,
            contactNo: "1234567006",
            address: "Hilltop Road",
            feesPaidUpto: Month.April,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "17/01/2013",
         },
         {
            username: "student7-class4",
            firstname: "Arjun",
            lastname: "Patel",
            motherName: "Nisha",
            fatherName: "Pankaj",
            gender: Gender.Male,
            contactNo: "1234567007",
            address: "Sunshine Avenue",
            feesPaidUpto: Month.March,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "03/07/2013",
         },
         {
            username: "student8-class4",
            firstname: "Saanvi",
            lastname: "Chawla",
            motherName: "Maya",
            fatherName: "Raghav",
            gender: Gender.Female,
            contactNo: "1234567008",
            address: "Peach Grove",
            feesPaidUpto: Month.May,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "19/02/2013",
         },
         {
            username: "student9-class4",
            firstname: "Aryan",
            lastname: "Singh",
            motherName: "Pooja",
            fatherName: "Suresh",
            gender: Gender.Male,
            contactNo: "1234567009",
            address: "Riverbank Road",
            feesPaidUpto: Month.April,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "28/11/2013",
         },
         {
            username: "student10-class4",
            firstname: "Diya",
            lastname: "Kumari",
            motherName: "Sarita",
            fatherName: "Sunil",
            gender: Gender.Female,
            contactNo: "1234567010",
            address: "Ocean View",
            feesPaidUpto: Month.June,
            classId: ClassList.class_4,
            admissionYear: 2024,
            dob: "09/05/2013",
         },

         // Class 5 Students
         {
            username: "student1-class5",
            firstname: "Aman",
            lastname: "Thakur",
            motherName: "Sunita",
            fatherName: "Rakesh",
            gender: Gender.Male,
            contactNo: "1234567011",
            address: "Valley Heights",
            feesPaidUpto: Month.April,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "25/03/2012",
         },
         {
            username: "student2-class5",
            firstname: "Jiya",
            lastname: "Verma",
            motherName: "Kavita",
            fatherName: "Harish",
            gender: Gender.Female,
            contactNo: "1234567012",
            address: "Bloomfield Street",
            feesPaidUpto: Month.May,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "14/06/2012",
         },
         {
            username: "student3-class5",
            firstname: "Dev",
            lastname: "Joshi",
            motherName: "Poonam",
            fatherName: "Vishal",
            gender: Gender.Male,
            contactNo: "1234567013",
            address: "New City Road",
            feesPaidUpto: Month.June,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "30/08/2012",
         },
         {
            username: "student4-class5",
            firstname: "Kritika",
            lastname: "Arora",
            motherName: "Ritu",
            fatherName: "Rajiv",
            gender: Gender.Female,
            contactNo: "1234567014",
            address: "Mountain View",
            feesPaidUpto: Month.March,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "18/09/2012",
         },
         {
            username: "student5-class5",
            firstname: "Siddharth",
            lastname: "Kumar",
            motherName: "Seema",
            fatherName: "Pradeep",
            gender: Gender.Male,
            contactNo: "1234567015",
            address: "Forest Lane",
            feesPaidUpto: Month.April,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "22/12/2012",
         },
         {
            username: "student6-class5",
            firstname: "Tanya",
            lastname: "Gupta",
            motherName: "Anjali",
            fatherName: "Raghav",
            gender: Gender.Female,
            contactNo: "1234567016",
            address: "Hill View",
            feesPaidUpto: Month.May,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "04/01/2012",
         },
         {
            username: "student7-class5",
            firstname: "Yash",
            lastname: "Singh",
            motherName: "Suman",
            fatherName: "Anil",
            gender: Gender.Male,
            contactNo: "1234567017",
            address: "Crescent Road",
            feesPaidUpto: Month.March,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "11/11/2012",
         },
         {
            username: "student8-class5",
            firstname: "Shivani",
            lastname: "Mehta",
            motherName: "Nisha",
            fatherName: "Manoj",
            gender: Gender.Female,
            contactNo: "1234567018",
            address: "City Park",
            feesPaidUpto: Month.April,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "23/05/2012",
         },
         {
            username: "student9-class5",
            firstname: "Ansh",
            lastname: "Rana",
            motherName: "Priya",
            fatherName: "Dinesh",
            gender: Gender.Male,
            contactNo: "1234567019",
            address: "Lakeside",
            feesPaidUpto: Month.May,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "13/02/2012",
         },
         {
            username: "student10-class5",
            firstname: "Riya",
            lastname: "Shukla",
            motherName: "Suman",
            fatherName: "Kumar",
            gender: Gender.Female,
            contactNo: "1234567020",
            address: "Garden Street",
            feesPaidUpto: Month.June,
            classId: ClassList.class_5,
            admissionYear: 2024,
            dob: "26/07/2012",
         },

         // Class 6 Students
         {
            username: "student1-class6",
            firstname: "Aditya",
            lastname: "Nath",
            motherName: "Vandana",
            fatherName: "Subhash",
            gender: Gender.Male,
            contactNo: "1234567021",
            address: "Greenwood",
            feesPaidUpto: Month.April,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "25/06/2011",
         },
         {
            username: "student2-class6",
            firstname: "Radhika",
            lastname: "Tiwari",
            motherName: "Neha",
            fatherName: "Shyam",
            gender: Gender.Female,
            contactNo: "1234567022",
            address: "Crystal Lane",
            feesPaidUpto: Month.May,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "14/09/2011",
         },
         {
            username: "student3-class6",
            firstname: "Nikhil",
            lastname: "Bansal",
            motherName: "Rajini",
            fatherName: "Rohit",
            gender: Gender.Male,
            contactNo: "1234567023",
            address: "Palm Heights",
            feesPaidUpto: Month.June,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "19/02/2011",
         },
         {
            username: "student4-class6",
            firstname: "Neha",
            lastname: "Reddy",
            motherName: "Pooja",
            fatherName: "Mohan",
            gender: Gender.Female,
            contactNo: "1234567024",
            address: "Skyline",
            feesPaidUpto: Month.March,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "09/05/2011",
         },
         {
            username: "student5-class6",
            firstname: "Sagar",
            lastname: "Patil",
            motherName: "Meenal",
            fatherName: "Santosh",
            gender: Gender.Male,
            contactNo: "1234567025",
            address: "Waterfront",
            feesPaidUpto: Month.April,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "03/08/2011",
         },
         {
            username: "student6-class6",
            firstname: "Simran",
            lastname: "Ghosh",
            motherName: "Pallavi",
            fatherName: "Arvind",
            gender: Gender.Female,
            contactNo: "1234567026",
            address: "Horizon View",
            feesPaidUpto: Month.May,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "27/01/2011",
         },
         {
            username: "student7-class6",
            firstname: "Karan",
            lastname: "Sharma",
            motherName: "Geeta",
            fatherName: "Sunil",
            gender: Gender.Male,
            contactNo: "1234567027",
            address: "Silver Springs",
            feesPaidUpto: Month.March,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "14/11/2011",
         },
         {
            username: "student8-class6",
            firstname: "Mehak",
            lastname: "Verma",
            motherName: "Shalini",
            fatherName: "Harvinder",
            gender: Gender.Female,
            contactNo: "1234567028",
            address: "Riverbank",
            feesPaidUpto: Month.April,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "05/02/2011",
         },
         {
            username: "student9-class6",
            firstname: "Ankit",
            lastname: "Pandey",
            motherName: "Sumita",
            fatherName: "Deepak",
            gender: Gender.Male,
            contactNo: "1234567029",
            address: "City Towers",
            feesPaidUpto: Month.May,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "02/07/2011",
         },
         {
            username: "student10-class6",
            firstname: "Aanya",
            lastname: "Kumar",
            motherName: "Sunita",
            fatherName: "Rajeev",
            gender: Gender.Female,
            contactNo: "1234567030",
            address: "Ocean Breeze",
            feesPaidUpto: Month.June,
            classId: ClassList.class_6,
            admissionYear: 2024,
            dob: "15/12/2011",
         },
         {
            username: "student1-class7",
            firstname: "Aarav",
            lastname: "Sharma",
            motherName: "Rita",
            fatherName: "Manoj",
            gender: Gender.Male,
            contactNo: "1234567031",
            address: "Greenwood",
            feesPaidUpto: Month.June,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "20/03/2010",
         },
         {
            username: "student2-class7",
            firstname: "Isha",
            lastname: "Mehta",
            motherName: "Anita",
            fatherName: "Vijay",
            gender: Gender.Female,
            contactNo: "1234567032",
            address: "Sunset Ridge",
            feesPaidUpto: Month.May,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "12/11/2010",
         },
         {
            username: "student3-class7",
            firstname: "Rohan",
            lastname: "Verma",
            motherName: "Sunita",
            fatherName: "Shankar",
            gender: Gender.Male,
            contactNo: "1234567033",
            address: "Hilltop",
            feesPaidUpto: Month.April,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "08/02/2010",
         },
         {
            username: "student4-class7",
            firstname: "Priya",
            lastname: "Gupta",
            motherName: "Neelam",
            fatherName: "Raghav",
            gender: Gender.Female,
            contactNo: "1234567034",
            address: "City Heights",
            feesPaidUpto: Month.March,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "21/07/2010",
         },
         {
            username: "student5-class7",
            firstname: "Vikram",
            lastname: "Patel",
            motherName: "Geeta",
            fatherName: "Ajay",
            gender: Gender.Male,
            contactNo: "1234567035",
            address: "Golden Oaks",
            feesPaidUpto: Month.May,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "17/04/2010",
         },
         {
            username: "student6-class7",
            firstname: "Ananya",
            lastname: "Shukla",
            motherName: "Rupal",
            fatherName: "Ashok",
            gender: Gender.Female,
            contactNo: "1234567036",
            address: "Silver Grove",
            feesPaidUpto: Month.June,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "30/01/2010",
         },
         {
            username: "student7-class7",
            firstname: "Siddharth",
            lastname: "Kumar",
            motherName: "Madhuri",
            fatherName: "Anil",
            gender: Gender.Male,
            contactNo: "1234567037",
            address: "Maple Avenue",
            feesPaidUpto: Month.April,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "05/06/2010",
         },
         {
            username: "student8-class7",
            firstname: "Neha",
            lastname: "Yadav",
            motherName: "Kiran",
            fatherName: "Deepak",
            gender: Gender.Female,
            contactNo: "1234567038",
            address: "Beachside",
            feesPaidUpto: Month.March,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "16/10/2010",
         },
         {
            username: "student9-class7",
            firstname: "Manish",
            lastname: "Rai",
            motherName: "Poonam",
            fatherName: "Mahesh",
            gender: Gender.Male,
            contactNo: "1234567039",
            address: "Park Avenue",
            feesPaidUpto: Month.May,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "01/12/2010",
         },
         {
            username: "student10-class7",
            firstname: "Sanya",
            lastname: "Singh",
            motherName: "Jasmin",
            fatherName: "Pankaj",
            gender: Gender.Female,
            contactNo: "1234567040",
            address: "Lakeside",
            feesPaidUpto: Month.June,
            classId: ClassList.class_7,
            admissionYear: 2024,
            dob: "10/05/2010",
         },

         // Class 8 Students
         {
            username: "student1-class8",
            firstname: "Kartik",
            lastname: "Chaudhary",
            motherName: "Pooja",
            fatherName: "Rohit",
            gender: Gender.Male,
            contactNo: "1234567041",
            address: "Riverwood",
            feesPaidUpto: Month.May,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "22/04/2009",
         },
         {
            username: "student2-class8",
            firstname: "Simran",
            lastname: "Arora",
            motherName: "Rajni",
            fatherName: "Suraj",
            gender: Gender.Female,
            contactNo: "1234567042",
            address: "Valley View",
            feesPaidUpto: Month.April,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "13/01/2009",
         },
         {
            username: "student3-class8",
            firstname: "Amit",
            lastname: "Kumar",
            motherName: "Neelam",
            fatherName: "Ravi",
            gender: Gender.Male,
            contactNo: "1234567043",
            address: "Sunshine Park",
            feesPaidUpto: Month.March,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "11/09/2009",
         },
         {
            username: "student4-class8",
            firstname: "Tanya",
            lastname: "Jain",
            motherName: "Shashi",
            fatherName: "Vikram",
            gender: Gender.Female,
            contactNo: "1234567044",
            address: "Cedar Heights",
            feesPaidUpto: Month.June,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "06/07/2009",
         },
         {
            username: "student5-class8",
            firstname: "Raj",
            lastname: "Verma",
            motherName: "Rekha",
            fatherName: "Ramesh",
            gender: Gender.Male,
            contactNo: "1234567045",
            address: "Moonlight Bay",
            feesPaidUpto: Month.May,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "30/03/2009",
         },
         {
            username: "student6-class8",
            firstname: "Meera",
            lastname: "Singh",
            motherName: "Suman",
            fatherName: "Arvind",
            gender: Gender.Female,
            contactNo: "1234567046",
            address: "Westwood",
            feesPaidUpto: Month.April,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "18/10/2009",
         },
         {
            username: "student7-class8",
            firstname: "Gaurav",
            lastname: "Patel",
            motherName: "Seema",
            fatherName: "Kiran",
            gender: Gender.Male,
            contactNo: "1234567047",
            address: "Cherry Blossom",
            feesPaidUpto: Month.March,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "25/06/2009",
         },
         {
            username: "student8-class8",
            firstname: "Ritika",
            lastname: "Kaur",
            motherName: "Saroj",
            fatherName: "Vineet",
            gender: Gender.Female,
            contactNo: "1234567048",
            address: "Bluebell Gardens",
            feesPaidUpto: Month.May,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "04/02/2009",
         },
         {
            username: "student9-class8",
            firstname: "Arjun",
            lastname: "Yadav",
            motherName: "Meena",
            fatherName: "Krishan",
            gender: Gender.Male,
            contactNo: "1234567049",
            address: "Seaside",
            feesPaidUpto: Month.June,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "09/12/2009",
         },
         {
            username: "student10-class8",
            firstname: "Sanya",
            lastname: "Sharma",
            motherName: "Shashi",
            fatherName: "Manish",
            gender: Gender.Female,
            contactNo: "1234567050",
            address: "Mountainview",
            feesPaidUpto: Month.April,
            classId: ClassList.class_8,
            admissionYear: 2024,
            dob: "19/08/2009",
         },

         // Class 9 Students
         {
            username: "student1-class9",
            firstname: "Ankit",
            lastname: "Shukla",
            motherName: "Neha",
            fatherName: "Nitin",
            gender: Gender.Male,
            contactNo: "1234567051",
            address: "Park Avenue",
            feesPaidUpto: Month.May,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "22/02/2008",
         },
         {
            username: "student2-class9",
            firstname: "Aditi",
            lastname: "Verma",
            motherName: "Anjali",
            fatherName: "Rajeev",
            gender: Gender.Female,
            contactNo: "1234567052",
            address: "Sunset View",
            feesPaidUpto: Month.April,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "11/12/2008",
         },
         {
            username: "student3-class9",
            firstname: "Kunal",
            lastname: "Patel",
            motherName: "Meena",
            fatherName: "Suraj",
            gender: Gender.Male,
            contactNo: "1234567053",
            address: "Golden Valley",
            feesPaidUpto: Month.March,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "15/03/2008",
         },
         {
            username: "student4-class9",
            firstname: "Neha",
            lastname: "Rai",
            motherName: "Shalini",
            fatherName: "Kumar",
            gender: Gender.Female,
            contactNo: "1234567054",
            address: "Bluewater",
            feesPaidUpto: Month.May,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "02/08/2008",
         },
         {
            username: "student5-class9",
            firstname: "Vishal",
            lastname: "Gupta",
            motherName: "Rekha",
            fatherName: "Suresh",
            gender: Gender.Male,
            contactNo: "1234567055",
            address: "Riverbank",
            feesPaidUpto: Month.June,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "27/05/2008",
         },
         {
            username: "student6-class9",
            firstname: "Riya",
            lastname: "Sinha",
            motherName: "Shubhi",
            fatherName: "Ashok",
            gender: Gender.Female,
            contactNo: "1234567056",
            address: "Palm Grove",
            feesPaidUpto: Month.April,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "17/10/2008",
         },
         {
            username: "student7-class9",
            firstname: "Sahil",
            lastname: "Chawla",
            motherName: "Anjali",
            fatherName: "Rajendra",
            gender: Gender.Male,
            contactNo: "1234567057",
            address: "Mountainview",
            feesPaidUpto: Month.March,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "10/02/2008",
         },
         {
            username: "student8-class9",
            firstname: "Sonali",
            lastname: "Kumar",
            motherName: "Suman",
            fatherName: "Anil",
            gender: Gender.Female,
            contactNo: "1234567058",
            address: "Oakwood",
            feesPaidUpto: Month.May,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "09/06/2008",
         },
         {
            username: "student9-class9",
            firstname: "Kavya",
            lastname: "Verma",
            motherName: "Sunita",
            fatherName: "Vikram",
            gender: Gender.Female,
            contactNo: "1234567059",
            address: "Lakeside",
            feesPaidUpto: Month.April,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "23/09/2008",
         },
         {
            username: "student10-class9",
            firstname: "Pranav",
            lastname: "Jain",
            motherName: "Neelam",
            fatherName: "Ramesh",
            gender: Gender.Male,
            contactNo: "1234567060",
            address: "Crystal Park",
            feesPaidUpto: Month.March,
            classId: ClassList.class_9,
            admissionYear: 2024,
            dob: "28/11/2008",
         },
         {
            username: "student1-class10",
            firstname: "Arjun",
            lastname: "Sharma",
            motherName: "Neelam",
            fatherName: "Rajesh",
            gender: Gender.Male,
            contactNo: "9876543210",
            address: "Green Park",
            feesPaidUpto: Month.April,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "15/07/2007",
         },
         {
            username: "student2-class10",
            firstname: "Priya",
            lastname: "Verma",
            motherName: "Geeta",
            fatherName: "Suresh",
            gender: Gender.Female,
            contactNo: "9123456789",
            address: "Sunrise Colony",
            feesPaidUpto: Month.March,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "23/11/2007",
         },
         {
            username: "student3-class10",
            firstname: "Vikram",
            lastname: "Singh",
            motherName: "Sarita",
            fatherName: "Manoj",
            gender: Gender.Male,
            contactNo: "8998776655",
            address: "Shiv Nagar",
            feesPaidUpto: Month.May,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "05/05/2007",
         },
         {
            username: "student4-class10",
            firstname: "Aditi",
            lastname: "Gupta",
            motherName: "Rekha",
            fatherName: "Vikas",
            gender: Gender.Female,
            contactNo: "8855223344",
            address: "Jai Hind Colony",
            feesPaidUpto: Month.February,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "18/09/2007",
         },
         {
            username: "student5-class10",
            firstname: "Rahul",
            lastname: "Yadav",
            motherName: "Suman",
            fatherName: "Ramesh",
            gender: Gender.Male,
            contactNo: "9988776655",
            address: "Vikram Singh Street",
            feesPaidUpto: Month.April,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "12/12/2007",
         },
         {
            username: "student6-class10",
            firstname: "Riya",
            lastname: "Patel",
            motherName: "Anju",
            fatherName: "Vinod",
            gender: Gender.Female,
            contactNo: "7676767676",
            address: "Brahma Nagar",
            feesPaidUpto: Month.June,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "02/03/2007",
         },
         {
            username: "student7-class10",
            firstname: "Karan",
            lastname: "Mehta",
            motherName: "Reena",
            fatherName: "Raghav",
            gender: Gender.Male,
            contactNo: "7777888899",
            address: "Saket City",
            feesPaidUpto: Month.March,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "25/08/2007",
         },
         {
            username: "student8-class10",
            firstname: "Nisha",
            lastname: "Rani",
            motherName: "Shweta",
            fatherName: "Krishan",
            gender: Gender.Female,
            contactNo: "6677889900",
            address: "Durganagar",
            feesPaidUpto: Month.July,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "30/06/2007",
         },
         {
            username: "student9-class10",
            firstname: "Aman",
            lastname: "Joshi",
            motherName: "Nisha",
            fatherName: "Kailash",
            gender: Gender.Male,
            contactNo: "8123456789",
            address: "Sector 14",
            feesPaidUpto: Month.March,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "17/10/2007",
         },
         {
            username: "student10-class10",
            firstname: "Seema",
            lastname: "Bansal",
            motherName: "Sumita",
            fatherName: "Ravinder",
            gender: Gender.Female,
            contactNo: "9546783210",
            address: "Sushant Lok",
            feesPaidUpto: Month.May,
            classId: ClassList.class_10,
            admissionYear: 2024,
            dob: "22/02/2007",
         },
         {
            username: "student1-class11",
            firstname: "Ishaan",
            lastname: "Khan",
            motherName: "Fatima",
            fatherName: "Shahnawaz",
            gender: Gender.Male,
            contactNo: "9087654321",
            address: "Azad Nagar",
            feesPaidUpto: Month.March,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "11/12/2006",
         },
         {
            username: "student2-class11",
            firstname: "Maya",
            lastname: "Patil",
            motherName: "Anjali",
            fatherName: "Vijay",
            gender: Gender.Female,
            contactNo: "9234786541",
            address: "Nashik Road",
            feesPaidUpto: Month.April,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "20/06/2006",
         },
         {
            username: "student3-class11",
            firstname: "Ravi",
            lastname: "Sharma",
            motherName: "Poonam",
            fatherName: "Raghav",
            gender: Gender.Male,
            contactNo: "9876541230",
            address: "Chandni Chowk",
            feesPaidUpto: Month.May,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "04/09/2006",
         },
         {
            username: "student4-class11",
            firstname: "Sanya",
            lastname: "Verma",
            motherName: "Neelam",
            fatherName: "Nand Kumar",
            gender: Gender.Female,
            contactNo: "9778855223",
            address: "Pune Vihar",
            feesPaidUpto: Month.June,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "13/11/2006",
         },
         {
            username: "student5-class11",
            firstname: "Tarun",
            lastname: "Singh",
            motherName: "Urmila",
            fatherName: "Suraj",
            gender: Gender.Male,
            contactNo: "9999888877",
            address: "Vishnu Nagar",
            feesPaidUpto: Month.April,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "22/10/2006",
         },
         {
            username: "student6-class11",
            firstname: "Khushboo",
            lastname: "Joshi",
            motherName: "Manju",
            fatherName: "Sanjay",
            gender: Gender.Female,
            contactNo: "9800112233",
            address: "Main Market",
            feesPaidUpto: Month.March,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "14/08/2006",
         },
         {
            username: "student7-class11",
            firstname: "Abhinav",
            lastname: "Kumar",
            motherName: "Suman",
            fatherName: "Ashok",
            gender: Gender.Male,
            contactNo: "9112345678",
            address: "Old City",
            feesPaidUpto: Month.February,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "27/05/2006",
         },
         {
            username: "student8-class11",
            firstname: "Tanya",
            lastname: "Rathore",
            motherName: "Leela",
            fatherName: "Vijendra",
            gender: Gender.Female,
            contactNo: "7991223344",
            address: "Shankar Vihar",
            feesPaidUpto: Month.April,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "19/09/2006",
         },
         {
            username: "student9-class11",
            firstname: "Harsh",
            lastname: "Yadav",
            motherName: "Geeta",
            fatherName: "Ajay",
            gender: Gender.Male,
            contactNo: "8234567890",
            address: "Bhubaneswar",
            feesPaidUpto: Month.May,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "07/02/2006",
         },
         {
            username: "student10-class11",
            firstname: "Ritu",
            lastname: "Kumar",
            motherName: "Sunita",
            fatherName: "Praveen",
            gender: Gender.Female,
            contactNo: "9123458790",
            address: "Kailash Hills",
            feesPaidUpto: Month.March,
            classId: ClassList.class_11,
            admissionYear: 2024,
            dob: "02/06/2006",
         },
         {
            username: "student1-class12",
            firstname: "Ankit",
            lastname: "Tiwari",
            motherName: "Savita",
            fatherName: "Pradeep",
            gender: Gender.Male,
            contactNo: "7776665555",
            address: "Sadar Bazar",
            feesPaidUpto: Month.May,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "02/10/2005",
         },
         {
            username: "student2-class12",
            firstname: "Sonal",
            lastname: "Mehta",
            motherName: "Komal",
            fatherName: "Devendra",
            gender: Gender.Female,
            contactNo: "9587456234",
            address: "Shree Nagar",
            feesPaidUpto: Month.April,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "19/04/2005",
         },
         {
            username: "student3-class12",
            firstname: "Puneet",
            lastname: "Gupta",
            motherName: "Manju",
            fatherName: "Shivendra",
            gender: Gender.Male,
            contactNo: "8123456789",
            address: "Civil Lines",
            feesPaidUpto: Month.March,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "08/12/2005",
         },
         {
            username: "student4-class12",
            firstname: "Tanya",
            lastname: "Sharma",
            motherName: "Maya",
            fatherName: "Vikas",
            gender: Gender.Female,
            contactNo: "9736452100",
            address: "Liberty Park",
            feesPaidUpto: Month.June,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "10/02/2005",
         },
         {
            username: "student5-class12",
            firstname: "Rohit",
            lastname: "Verma",
            motherName: "Neelam",
            fatherName: "Rajesh",
            gender: Gender.Male,
            contactNo: "9888776655",
            address: "Satyam Colony",
            feesPaidUpto: Month.March,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "22/11/2005",
         },
         {
            username: "student6-class12",
            firstname: "Divya",
            lastname: "Patel",
            motherName: "Rekha",
            fatherName: "Ashwin",
            gender: Gender.Female,
            contactNo: "9922334455",
            address: "Sadar Bazaar",
            feesPaidUpto: Month.May,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "29/03/2005",
         },
         {
            username: "student7-class12",
            firstname: "Manish",
            lastname: "Kumar",
            motherName: "Shashi",
            fatherName: "Mukesh",
            gender: Gender.Male,
            contactNo: "8776655444",
            address: "Durgapur",
            feesPaidUpto: Month.April,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "25/06/2005",
         },
         {
            username: "student8-class12",
            firstname: "Shivani",
            lastname: "Rani",
            motherName: "Sumita",
            fatherName: "Ravindra",
            gender: Gender.Female,
            contactNo: "7632145678",
            address: "Sector 18",
            feesPaidUpto: Month.February,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "14/08/2005",
         },
         {
            username: "student9-class12",
            firstname: "Aditya",
            lastname: "Joshi",
            motherName: "Ranjana",
            fatherName: "Vikash",
            gender: Gender.Male,
            contactNo: "7777899000",
            address: "Rajinder Nagar",
            feesPaidUpto: Month.May,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "16/09/2005",
         },
         {
            username: "student10-class12",
            firstname: "Nikita",
            lastname: "Patil",
            motherName: "Anjali",
            fatherName: "Rajesh",
            gender: Gender.Female,
            contactNo: "9123345678",
            address: "Kandivali",
            feesPaidUpto: Month.June,
            classId: ClassList.class_12,
            admissionYear: 2024,
            dob: "05/01/2005",
         }
      ],
   });

   await prisma.expense.createMany({
      data: [
         {
            monthName: Month.January,
            date: 24,
            amount: 12500,
            year: 2024,
            description: "School maintenance check",
            title: "School Inspection",
         },
         {
            monthName: Month.March,
            date: 1,
            amount: 8250,
            year: 2024,
            description: "Annual Function Expense for all classes",
            title: "Annual Function 2024",
         },
         {
            monthName: Month.February,
            date: 14,
            amount: 10500,
            year: 2024,
            description: "Valentine's Day Celebration Setup",
            title: "Special Day Event",
         },
         {
            monthName: Month.April,
            date: 5,
            amount: 17500,
            year: 2024,
            description: "Teacher Training Program",
            title: "Professional Development",
         },
         {
            monthName: Month.May,
            date: 20,
            amount: 15200,
            year: 2024,
            description: "Science Fair and Setup",
            title: "Science Exhibition",
         },
         {
            monthName: Month.June,
            date: 10,
            amount: 8900,
            year: 2024,
            description: "Sports Day Arrangements",
            title: "Sports Day Expense",
         },
         {
            monthName: Month.July,
            date: 18,
            amount: 13450,
            year: 2024,
            description: "Maintenance of School Buses",
            title: "Transport Maintenance",
         },
         {
            monthName: Month.August,
            date: 25,
            amount: 16800,
            year: 2024,
            description: "Independence Day Celebrations",
            title: "National Event Expense",
         },
         {
            monthName: Month.September,
            date: 12,
            amount: 14600,
            year: 2024,
            description: "Exam Paper Printing",
            title: "Examination Costs",
         },
         {
            monthName: Month.October,
            date: 8,
            amount: 12900,
            year: 2024,
            description: "Library Book Purchases",
            title: "Library Upgrades",
         },
         {
            monthName: Month.November,
            date: 3,
            amount: 15700,
            year: 2024,
            description: "Cultural Fest Expenses",
            title: "Cultural Festival",
         },
         {
            monthName: Month.December,
            date: 15,
            amount: 19000,
            year: 2024,
            description: "Christmas Celebration Arrangements",
            title: "Christmas Festivity",
         },
         // Adding data for other years
         {
            monthName: Month.January,
            date: 10,
            amount: 9200,
            year: 2023,
            description: "New Year Celebration Expense",
            title: "New Year Event",
         },
         {
            monthName: Month.March,
            date: 25,
            amount: 10250,
            year: 2023,
            description: "Annual Day Celebrations",
            title: "Annual Day 2023",
         },
         {
            monthName: Month.June,
            date: 5,
            amount: 7400,
            year: 2023,
            description: "School Gardening Project",
            title: "Green Initiative",
         },
         {
            monthName: Month.September,
            date: 15,
            amount: 13200,
            year: 2023,
            description: "Teachers' Day Celebrations",
            title: "Teachers' Day 2023",
         },
         {
            monthName: Month.December,
            date: 20,
            amount: 15800,
            year: 2023,
            description: "End of Year Party",
            title: "Year-End Celebration",
         },
         {
            monthName: Month.February,
            date: 28,
            amount: 11200,
            year: 2022,
            description: "Sports Equipment Purchase",
            title: "Sports Investment",
         },
         {
            monthName: Month.May,
            date: 15,
            amount: 13850,
            year: 2022,
            description: "Building Repair and Maintenance",
            title: "Infrastructure Costs",
         },
         {
            monthName: Month.August,
            date: 18,
            amount: 15400,
            year: 2022,
            description: "New Admission Advertisement",
            title: "Marketing Expense",
         },
         {
            monthName: Month.November,
            date: 12,
            amount: 12950,
            year: 2022,
            description: "Diwali Celebration Setup",
            title: "Festival Arrangements",
         },
         {
            monthName: Month.January,
            date: 22,
            amount: 8700,
            year: 2021,
            description: "Classroom Furniture Upgrade",
            title: "Furniture Purchase",
         },
         {
            monthName: Month.April,
            date: 10,
            amount: 15200,
            year: 2021,
            description: "Teacher's Workshop",
            title: "Skill Development",
         },
         {
            monthName: Month.July,
            date: 30,
            amount: 9200,
            year: 2021,
            description: "Playground Equipment",
            title: "Outdoor Upgrade",
         },
         {
            monthName: Month.October,
            date: 18,
            amount: 12550,
            year: 2021,
            description: "Festival Light Setup",
            title: "Decorations",
         },
      ],
   });

   await prisma.gain.createMany({
      data: [
         // Year 2021
         { monthName: Month.January, date: 15, amount: 50000, year: 2021, description: "Tuition Fees", title: "Monthly Tuition" },
         { monthName: Month.February, date: 20, amount: 15000, year: 2021, description: "Annual Sports Day Revenue", title: "Event Revenue" },
         { monthName: Month.March, date: 10, amount: 12000, year: 2021, description: "Science Exhibition Tickets", title: "Exhibition Revenue" },
         { monthName: Month.April, date: 5, amount: 25000, year: 2021, description: "Grants for Education", title: "Government Grant" },
         { monthName: Month.May, date: 18, amount: 30000, year: 2021, description: "Summer Camp Fees", title: "Summer Camp" },
         { monthName: Month.June, date: 25, amount: 20000, year: 2021, description: "Donation from Alumni", title: "Alumni Donation" },
         { monthName: Month.July, date: 7, amount: 8000, year: 2021, description: "Library Membership Fees", title: "Library Fees" },
         { monthName: Month.August, date: 12, amount: 18000, year: 2021, description: "Cultural Event Tickets", title: "Event Revenue" },
         { monthName: Month.September, date: 20, amount: 40000, year: 2021, description: "Quarterly Tuition Fees", title: "Tuition Income" },
         { monthName: Month.October, date: 5, amount: 15000, year: 2021, description: "Annual Fest Sponsorship", title: "Event Sponsorship" },
         { monthName: Month.November, date: 15, amount: 25000, year: 2021, description: "Scholarship Grant", title: "Government Grant" },
         { monthName: Month.December, date: 28, amount: 35000, year: 2021, description: "Winter Workshop Fees", title: "Workshop Income" },

         // Year 2022
         { monthName: Month.January, date: 15, amount: 55000, year: 2022, description: "Tuition Fees", title: "Monthly Tuition" },
         { monthName: Month.February, date: 20, amount: 17000, year: 2022, description: "Valentine's Day Event", title: "Event Revenue" },
         { monthName: Month.March, date: 10, amount: 13000, year: 2022, description: "Arts Exhibition Tickets", title: "Exhibition Revenue" },
         { monthName: Month.April, date: 5, amount: 27000, year: 2022, description: "Annual Grant", title: "Government Grant" },
         { monthName: Month.May, date: 18, amount: 32000, year: 2022, description: "Summer Camp Fees", title: "Summer Camp" },
         { monthName: Month.June, date: 25, amount: 22000, year: 2022, description: "Corporate Donation", title: "Donation" },
         { monthName: Month.July, date: 7, amount: 8500, year: 2022, description: "Library Membership Fees", title: "Library Fees" },
         { monthName: Month.August, date: 12, amount: 20000, year: 2022, description: "Cultural Event Tickets", title: "Event Revenue" },
         { monthName: Month.September, date: 20, amount: 42000, year: 2022, description: "Quarterly Tuition Fees", title: "Tuition Income" },
         { monthName: Month.October, date: 5, amount: 17000, year: 2022, description: "Annual Fest Sponsorship", title: "Event Sponsorship" },
         { monthName: Month.November, date: 15, amount: 26000, year: 2022, description: "Scholarship Grant", title: "Government Grant" },
         { monthName: Month.December, date: 28, amount: 36000, year: 2022, description: "Winter Workshop Fees", title: "Workshop Income" },

         // Year 2023
         { monthName: Month.January, date: 15, amount: 58000, year: 2023, description: "Tuition Fees", title: "Monthly Tuition" },
         { monthName: Month.February, date: 20, amount: 19000, year: 2023, description: "Annual Sports Event", title: "Event Revenue" },
         { monthName: Month.March, date: 10, amount: 14000, year: 2023, description: "Book Fair Revenue", title: "Fair Revenue" },
         { monthName: Month.April, date: 5, amount: 30000, year: 2023, description: "Educational Grant", title: "Government Grant" },
         { monthName: Month.May, date: 18, amount: 35000, year: 2023, description: "Summer Camp Income", title: "Camp Revenue" },
         { monthName: Month.June, date: 25, amount: 24000, year: 2023, description: "Alumni Donation", title: "Donation" },
         { monthName: Month.July, date: 7, amount: 9500, year: 2023, description: "Library Membership", title: "Library Income" },
         { monthName: Month.August, date: 12, amount: 22000, year: 2023, description: "Drama Event Tickets", title: "Event Revenue" },
         { monthName: Month.September, date: 20, amount: 44000, year: 2023, description: "Quarterly Tuition Fees", title: "Tuition Fees" },
         { monthName: Month.October, date: 5, amount: 19000, year: 2023, description: "Fest Sponsorship", title: "Event Sponsorship" },
         { monthName: Month.November, date: 15, amount: 28000, year: 2023, description: "Scholarship Grant", title: "Government Grant" },
         { monthName: Month.December, date: 28, amount: 38000, year: 2023, description: "Coding Bootcamp Income", title: "Bootcamp Revenue" },

         // Year 2024
         { monthName: Month.January, date: 15, amount: 60000, year: 2024, description: "Tuition Fees", title: "Monthly Tuition" },
         { monthName: Month.February, date: 20, amount: 20000, year: 2024, description: "Valentine's Charity Event", title: "Event Revenue" },
         { monthName: Month.March, date: 10, amount: 15000, year: 2024, description: "Spring Fair Income", title: "Fair Revenue" },
         { monthName: Month.April, date: 5, amount: 32000, year: 2024, description: "State Grant", title: "Government Grant" },
         { monthName: Month.May, date: 18, amount: 38000, year: 2024, description: "Summer Camp", title: "Camp Revenue" },
         { monthName: Month.June, date: 25, amount: 26000, year: 2024, description: "Corporate Donations", title: "Donation" },
         { monthName: Month.July, date: 7, amount: 10500, year: 2024, description: "Library Membership", title: "Library Income" },
         { monthName: Month.August, date: 12, amount: 24000, year: 2024, description: "Drama Competition Tickets", title: "Event Revenue" },
         { monthName: Month.September, date: 20, amount: 46000, year: 2024, description: "Quarterly Tuition", title: "Tuition Fees" },
         { monthName: Month.October, date: 5, amount: 21000, year: 2024, description: "Annual Fest", title: "Event Sponsorship" },
         { monthName: Month.November, date: 15, amount: 30000, year: 2024, description: "Scholarship Grant", title: "Grant Income" },
         { monthName: Month.December, date: 28, amount: 40000, year: 2024, description: "AI Workshop", title: "Workshop Revenue" },
      ],
   });

   await prisma.teacher.createMany({
      data: [
         {
            username: "first-Teacher",
            firstname: "Suman",
            lastname: "Lavesh",
            qualification: "B.Tech",
            joiningDate: 5,
            joiningYear: 2021,
            joiningMonth: Month.February,
            gender: Gender.Female,
            lastSalaryPaid: Month.August,
            contactNo: "1234567895",
            address: "Near student home",
            salary: 45290,
            subjects: [
               { subjects: ["Maths", "Physics"], classname: "class_12" },
               { subjects: ["Maths", "Physics"], classname: "class_11" },
            ],
         },
         {
            username: "second-Teacher",
            firstname: "Rajesh",
            lastname: "Kumar",
            qualification: "M.Sc",
            joiningDate: 15,
            joiningYear: 2020,
            joiningMonth: Month.January,
            gender: Gender.Male,
            lastSalaryPaid: Month.September,
            contactNo: "9876543210",
            address: "Teacher colony",
            salary: 40250,
            subjects: [
               { subjects: ["Science", "Biology"], classname: "class_10" },
               { subjects: ["Science", "Biology"], classname: "class_9" },
            ],
         },
         {
            username: "third-Teacher",
            firstname: "Anita",
            lastname: "Sharma",
            qualification: "M.A",
            joiningDate: 10,
            joiningYear: 2022,
            joiningMonth: Month.March,
            gender: Gender.Female,
            lastSalaryPaid: Month.October,
            contactNo: "1234509876",
            address: "Near school park",
            salary: 35500,
            subjects: [
               { subjects: ["English", "Hindi"], classname: "class_8" },
               { subjects: ["English", "Hindi"], classname: "class_7" },
            ],
         },
         {
            username: "fourth-Teacher",
            firstname: "Manoj",
            lastname: "Verma",
            qualification: "Ph.D",
            joiningDate: 20,
            joiningYear: 2019,
            joiningMonth: Month.May,
            gender: Gender.Male,
            lastSalaryPaid: Month.July,
            contactNo: "7654321980",
            address: "Town center",
            salary: 50200,
            subjects: [
               { subjects: ["SocialStudies", "History"], classname: "class_6" },
               { subjects: ["SocialStudies", "History"], classname: "class_5" },
            ],
         },
         {
            username: "fifth-Teacher",
            firstname: "Seema",
            lastname: "Rathore",
            qualification: "B.Ed",
            joiningDate: 8,
            joiningYear: 2023,
            joiningMonth: Month.July,
            gender: Gender.Female,
            lastSalaryPaid: Month.November,
            contactNo: "1122334455",
            address: "Village road",
            salary: 30000,
            subjects: [
               { subjects: ["ArtCraft", "ComputerScience"], classname: "class_4" },
            ],
         },
         {
            username: "sixth-Teacher",
            firstname: "Ravi",
            lastname: "Singh",
            qualification: "M.Sc",
            joiningDate: 12,
            joiningYear: 2021,
            joiningMonth: Month.April,
            gender: Gender.Male,
            lastSalaryPaid: Month.December,
            contactNo: "9988776655",
            address: "Market street",
            salary: 48000,
            subjects: [
               { subjects: ["Chemistry", "Biology"], classname: "class_12" },
               { subjects: ["Chemistry", "Biology"], classname: "class_11" },
            ],
         },
         {
            username: "seventh-Teacher",
            firstname: "Neha",
            lastname: "Gupta",
            qualification: "M.A",
            joiningDate: 22,
            joiningYear: 2020,
            joiningMonth: Month.September,
            gender: Gender.Female,
            lastSalaryPaid: Month.October,
            contactNo: "5432167890",
            address: "City center",
            salary: 42000,
            subjects: [
               { subjects: ["English", "History"], classname: "class_10" },
               { subjects: ["English", "History"], classname: "class_9" },
            ],
         },
         {
            username: "eighth-Teacher",
            firstname: "Arvind",
            lastname: "Yadav",
            qualification: "B.A",
            joiningDate: 7,
            joiningYear: 2022,
            joiningMonth: Month.August,
            gender: Gender.Male,
            lastSalaryPaid: Month.November,
            contactNo: "6543210987",
            address: "Highway road",
            salary: 35000,
            subjects: [
               { subjects: ["Maths", "SocialStudies"], classname: "class_8" },
               { subjects: ["Maths", "SocialStudies"], classname: "class_7" },
            ],
         },
         {
            username: "ninth-Teacher",
            firstname: "Pooja",
            lastname: "Mehta",
            qualification: "Ph.D",
            joiningDate: 5,
            joiningYear: 2018,
            joiningMonth: Month.May,
            gender: Gender.Female,
            lastSalaryPaid: Month.December,
            contactNo: "1239876540",
            address: "Near main gate",
            salary: 51000,
            subjects: [
               { subjects: ["Physics", "Chemistry"], classname: "class_12" },
               { subjects: ["Physics", "Chemistry"], classname: "class_11" },
            ],
         },
         {
            username: "tenth-Teacher",
            firstname: "Suresh",
            lastname: "Reddy",
            qualification: "M.Ed",
            joiningDate: 18,
            joiningYear: 2019,
            joiningMonth: Month.June,
            gender: Gender.Male,
            lastSalaryPaid: Month.October,
            contactNo: "5432109876",
            address: "Suburb street",
            salary: 47000,
            subjects: [
               { subjects: ["Geography", "ArtCraft"], classname: "class_6" },
               { subjects: ["Geography", "ArtCraft"], classname: "class_5" },
            ],
         },
      ],
   });

};
run().then(() => {
  prisma.$disconnect();
});
